#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# MOD-App
# Copyright (C) 2014-2015 Filipe Coelho <falktx@falktx.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of
# the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License see the LICENSE file.

# ------------------------------------------------------------------------------------------------------------
# Imports (Custom)

from mod_remote import *

# ------------------------------------------------------------------------------------------------------------
# Imports (Global)

if config_UseQt5:
    from PyQt5.QtCore import Qt
    from PyQt5.QtWidgets import QApplication
else:
    from PyQt4.QtCore import Qt
    from PyQt4.QtGui import QApplication

# ------------------------------------------------------------------------------------------------------------
# Import Signal

from signal import signal, SIGINT, SIGTERM

# ------------------------------------------------------------------------------------------------------------
# Global gui object

global gui
gui = None

# ------------------------------------------------------------------------------------------------------------
# Signal handler

def signalHandler(sig, frame):
    global gui
    if gui is None:
        return

    if sig in (SIGINT, SIGTERM):
        gui.SIGTERM.emit()

def setUpSignals():
    signal(SIGINT,  signalHandler)
    signal(SIGTERM, signalHandler)

# ------------------------------------------------------------------------------------------------------------
# Main

if __name__ == '__main__':
    # --------------------------------------------------------------------------------------------------------
    # App initialization

    QApplication.addLibraryPath(CWD)

    app = QApplication(sys.argv)
    app.setApplicationName("MOD-Remote")
    app.setApplicationVersion(config["version"])
    app.setOrganizationName("MOD")
    app.setWindowIcon(QIcon(":/48x48/mod.png"))

    if MACOS:
        app.setAttribute(Qt.AA_DontShowIconsInMenus)

    # --------------------------------------------------------------------------------------------------------
    # Set-up custom signal handling

    setUpSignals()

    # --------------------------------------------------------------------------------------------------------
    # Create GUI

    gui = RemoteWindow()

    # --------------------------------------------------------------------------------------------------------
    # Load project file if set

    #if len(sys.argv) > 1:
        #arg = sys.argv[-1]

        #if os.path.exists(arg):
            #gui.loadProjectLater(arg)

    # --------------------------------------------------------------------------------------------------------
    # Show GUI

    gui.show()

    # --------------------------------------------------------------------------------------------------------
    # App-Loop

    sys.exit(app.exec_())

# ------------------------------------------------------------------------------------------------------------
