#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# MOD-App
# Copyright (C) 2014-2015 Filipe Coelho <falktx@falktx.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of
# the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License see the LICENSE file.

# ------------------------------------------------------------------------------------------------------------
# Imports (Custom)

from mod_host import *

# ------------------------------------------------------------------------------------------------------------
# Imports (Global)

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication

# ------------------------------------------------------------------------------------------------------------
# Import Signal

from signal import signal, SIGINT, SIGTERM

try:
    from signal import SIGUSR1
    haveSIGUSR1 = True
except:
    haveSIGUSR1 = False

# ------------------------------------------------------------------------------------------------------------
# Global gui object

global gui
gui = None

# ------------------------------------------------------------------------------------------------------------
# Signal handler

def signalHandler(sig, frame):
    global gui
    if gui is None:
        return

    if sig in (SIGINT, SIGTERM):
        gui.SIGTERM.emit()
    elif haveSIGUSR1 and sig == SIGUSR1:
        gui.SIGUSR1.emit()

def setUpSignals():
    signal(SIGINT,  signalHandler)
    signal(SIGTERM, signalHandler)

    if not haveSIGUSR1:
        return

    signal(SIGUSR1, signalHandler)

# ------------------------------------------------------------------------------------------------------------
# Main

if __name__ == '__main__':
    # --------------------------------------------------------------------------------------------------------
    # App initialization

    QApplication.addLibraryPath(CWD)

    app = QApplication(sys.argv)
    app.setApplicationName("MOD-App")
    app.setApplicationVersion(config["version"])
    app.setOrganizationName("MOD")
    app.setWindowIcon(QIcon(":/48x48/mod.png"))

    if MACOS:
        app.setAttribute(Qt.AA_DontShowIconsInMenus)

    # --------------------------------------------------------------------------------------------------------
    # Set-up custom signal handling

    setUpSignals()

    # --------------------------------------------------------------------------------------------------------
    # Create Splash screen

    gui = HostSplashScreen()
    gui.rescanIfNeeded()

    # --------------------------------------------------------------------------------------------------------
    # Create GUI

    gui = HostWindow(gui)

    # --------------------------------------------------------------------------------------------------------
    # Load project file if set

    if len(sys.argv) > 1:
        arg = sys.argv[-1]

        if os.path.exists(arg):
            gui.openPedalboardLater(arg)

    # --------------------------------------------------------------------------------------------------------
    # Show GUI

    gui.show()

    # --------------------------------------------------------------------------------------------------------
    # App-Loop

    sys.exit(app.exec_())

# ------------------------------------------------------------------------------------------------------------
