#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# MOD-App
# Copyright (C) 2014-2015 Filipe Coelho <falktx@falktx.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of
# the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License see the LICENSE file.

# ------------------------------------------------------------------------------------------------------------
# Imports (Custom)

from mod_host import *

# ------------------------------------------------------------------------------------------------------------
# Imports (Global)

from PyQt5.QtCore import Qt
from PyQt5.QtWebKit import qWebKitMajorVersion
from PyQt5.QtWidgets import QApplication, QMessageBox

# ------------------------------------------------------------------------------------------------------------
# Import Signal

from signal import signal, SIGINT, SIGTERM

try:
    from signal import SIGUSR1
    haveSIGUSR1 = True
except:
    haveSIGUSR1 = False

# ------------------------------------------------------------------------------------------------------------
# Global gui object

global gui
gui = None

# ------------------------------------------------------------------------------------------------------------
# Signal handler

def signalHandler(sig, frame):
    global gui
    if gui is None:
        return

    if sig in (SIGINT, SIGTERM):
        gui.SIGTERM.emit()
    elif haveSIGUSR1 and sig == SIGUSR1:
        gui.SIGUSR1.emit()

def setUpSignals():
    signal(SIGINT,  signalHandler)
    signal(SIGTERM, signalHandler)

    if not haveSIGUSR1:
        return

    signal(SIGUSR1, signalHandler)

# ------------------------------------------------------------------------------------------------------------
# Main

if __name__ == '__main__':
    # --------------------------------------------------------------------------------------------------------
    # App initialization

    QApplication.addLibraryPath(CWD)

    app = QApplication(sys.argv)
    app.setApplicationName("MOD-App")
    app.setApplicationVersion(config["version"])
    app.setOrganizationName("MOD")
    app.setWindowIcon(QIcon(":/scalable/mod.svg"))

    if MACOS:
        app.setAttribute(Qt.AA_DontShowIconsInMenus)

    if qWebKitMajorVersion() < 538:
        QMessageBox.warning(None,
                            "MOD-App Alert", # app.translate("HostWindow", ), #app.translate("HostWindow",
                            """
                              The WebKit included in your distribution's PyQt5 package is too old!<br/>
                              You might experience graphical issues in MOD-App.
                            """,
                            QMessageBox.Ok)

    forcedRescanMode = HostSplashScreen.kRescanNull
    pedalboardToLoad = ""

    # --------------------------------------------------------------------------------------------------------
    # Set-up custom signal handling

    setUpSignals()

    # --------------------------------------------------------------------------------------------------------
    # Check arguments

    if len(sys.argv) > 1:
        arg = sys.argv[-1]

        if arg.startswith("--scan-lv2"):
            forcedRescanMode = HostSplashScreen.kRescanAll if arg == "--scan-lv2-all" else HostSplashScreen.kRescanMOD

        elif os.path.exists(arg):
            pedalboardToLoad = arg

    # --------------------------------------------------------------------------------------------------------
    # Create Splash screen

    gui = HostSplashScreen(forcedRescanMode)
    gui.rescanIfNeeded()

    # --------------------------------------------------------------------------------------------------------
    # Create GUI

    gui = HostWindow(gui)

    if pedalboardToLoad:
        gui.openPedalboardLater(pedalboardToLoad)

    # --------------------------------------------------------------------------------------------------------
    # Show GUI

    gui.show()

    # --------------------------------------------------------------------------------------------------------
    # App-Loop

    sys.exit(app.exec_())

# ------------------------------------------------------------------------------------------------------------
