#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# MOD-App
# Copyright (C) 2014-2015 Filipe Coelho <falktx@falktx.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of
# the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License see the LICENSE file.

# ------------------------------------------------------------------------------------------------------------
# Imports (Custom)

from mod_host import *

# ------------------------------------------------------------------------------------------------------------
# Imports (Global)

if using_Qt4:
    from PyQt4.QtCore import Qt
    from PyQt4.QtGui import QApplication, QColor, QMessageBox, QPalette
    from PyQt4.QtWebKit import qWebKitMajorVersion
else:
    from PyQt5.QtCore import Qt
    from PyQt5.QtGui import QColor, QPalette
    from PyQt5.QtWebKit import qWebKitMajorVersion
    from PyQt5.QtWidgets import QApplication, QMessageBox

# ------------------------------------------------------------------------------------------------------------
# Import Signal

from signal import signal, SIGINT, SIGTERM

try:
    from signal import SIGUSR1
    haveSIGUSR1 = True
except:
    haveSIGUSR1 = False

# ------------------------------------------------------------------------------------------------------------
# Global gui object

global gui
gui = None

# ------------------------------------------------------------------------------------------------------------
# Signal handler

def signalHandler(sig, frame):
    global gui
    if gui is None:
        return

    if sig in (SIGINT, SIGTERM):
        gui.SIGTERM.emit()
    elif haveSIGUSR1 and sig == SIGUSR1:
        gui.SIGUSR1.emit()

def setUpSignals():
    signal(SIGINT,  signalHandler)
    signal(SIGTERM, signalHandler)

    if not haveSIGUSR1:
        return

    signal(SIGUSR1, signalHandler)

# ------------------------------------------------------------------------------------------------------------
# Main

if __name__ == '__main__':
    # --------------------------------------------------------------------------------------------------------
    # App initialization

    QApplication.addLibraryPath(CWD)

    app = QApplication(sys.argv)
    app.setApplicationName("MOD-App")
    app.setApplicationVersion(config["version"])
    app.setOrganizationName("MOD")
    app.setWindowIcon(QIcon(":/scalable/mod.svg"))

    if MACOS:
        app.setAttribute(Qt.AA_DontShowIconsInMenus)

    if USING_LIVE_ISO:
        palette = QPalette()
        palette.setColor(QPalette.Disabled, QPalette.Window, QColor(14, 14, 14))
        palette.setColor(QPalette.Active,   QPalette.Window, QColor(17, 17, 17))
        palette.setColor(QPalette.Inactive, QPalette.Window, QColor(17, 17, 17))
        palette.setColor(QPalette.Disabled, QPalette.WindowText, QColor(83, 83, 83))
        palette.setColor(QPalette.Active,   QPalette.WindowText, QColor(240, 240, 240))
        palette.setColor(QPalette.Inactive, QPalette.WindowText, QColor(240, 240, 240))
        palette.setColor(QPalette.Disabled, QPalette.Base, QColor(6, 6, 6))
        palette.setColor(QPalette.Active,   QPalette.Base, QColor(7, 7, 7))
        palette.setColor(QPalette.Inactive, QPalette.Base, QColor(7, 7, 7))
        palette.setColor(QPalette.Disabled, QPalette.AlternateBase, QColor(12, 12, 12))
        palette.setColor(QPalette.Active,   QPalette.AlternateBase, QColor(14, 14, 14))
        palette.setColor(QPalette.Inactive, QPalette.AlternateBase, QColor(14, 14, 14))
        palette.setColor(QPalette.Disabled, QPalette.ToolTipBase, QColor(4, 4, 4))
        palette.setColor(QPalette.Active,   QPalette.ToolTipBase, QColor(4, 4, 4))
        palette.setColor(QPalette.Inactive, QPalette.ToolTipBase, QColor(4, 4, 4))
        palette.setColor(QPalette.Disabled, QPalette.ToolTipText, QColor(230, 230, 230))
        palette.setColor(QPalette.Active,   QPalette.ToolTipText, QColor(230, 230, 230))
        palette.setColor(QPalette.Inactive, QPalette.ToolTipText, QColor(230, 230, 230))
        palette.setColor(QPalette.Disabled, QPalette.Text, QColor(74, 74, 74))
        palette.setColor(QPalette.Active,   QPalette.Text, QColor(230, 230, 230))
        palette.setColor(QPalette.Inactive, QPalette.Text, QColor(230, 230, 230))
        palette.setColor(QPalette.Disabled, QPalette.Button, QColor(24, 24, 24))
        palette.setColor(QPalette.Active,   QPalette.Button, QColor(28, 28, 28))
        palette.setColor(QPalette.Inactive, QPalette.Button, QColor(28, 28, 28))
        palette.setColor(QPalette.Disabled, QPalette.ButtonText, QColor(90, 90, 90))
        palette.setColor(QPalette.Active,   QPalette.ButtonText, QColor(240, 240, 240))
        palette.setColor(QPalette.Inactive, QPalette.ButtonText, QColor(240, 240, 240))
        palette.setColor(QPalette.Disabled, QPalette.BrightText, QColor(255, 255, 255))
        palette.setColor(QPalette.Active,   QPalette.BrightText, QColor(255, 255, 255))
        palette.setColor(QPalette.Inactive, QPalette.BrightText, QColor(255, 255, 255))
        palette.setColor(QPalette.Disabled, QPalette.Light, QColor(191, 191, 191))
        palette.setColor(QPalette.Active,   QPalette.Light, QColor(191, 191, 191))
        palette.setColor(QPalette.Inactive, QPalette.Light, QColor(191, 191, 191))
        palette.setColor(QPalette.Disabled, QPalette.Midlight, QColor(155, 155, 155))
        palette.setColor(QPalette.Active,   QPalette.Midlight, QColor(155, 155, 155))
        palette.setColor(QPalette.Inactive, QPalette.Midlight, QColor(155, 155, 155))
        palette.setColor(QPalette.Disabled, QPalette.Dark, QColor(129, 129, 129))
        palette.setColor(QPalette.Active,   QPalette.Dark, QColor(129, 129, 129))
        palette.setColor(QPalette.Inactive, QPalette.Dark, QColor(129, 129, 129))
        palette.setColor(QPalette.Disabled, QPalette.Mid, QColor(94, 94, 94))
        palette.setColor(QPalette.Active,   QPalette.Mid, QColor(94, 94, 94))
        palette.setColor(QPalette.Inactive, QPalette.Mid, QColor(94, 94, 94))
        palette.setColor(QPalette.Disabled, QPalette.Shadow, QColor(155, 155, 155))
        palette.setColor(QPalette.Active,   QPalette.Shadow, QColor(155, 155, 155))
        palette.setColor(QPalette.Inactive, QPalette.Shadow, QColor(155, 155, 155))
        palette.setColor(QPalette.Disabled, QPalette.Highlight, QColor(14, 14, 14))
        palette.setColor(QPalette.Active,   QPalette.Highlight, QColor(60, 60, 60))
        palette.setColor(QPalette.Inactive, QPalette.Highlight, QColor(34, 34, 34))
        palette.setColor(QPalette.Disabled, QPalette.HighlightedText, QColor(83, 83, 83))
        palette.setColor(QPalette.Active,   QPalette.HighlightedText, QColor(255, 255, 255))
        palette.setColor(QPalette.Inactive, QPalette.HighlightedText, QColor(240, 240, 240))
        palette.setColor(QPalette.Disabled, QPalette.Link, QColor(34, 34, 74))
        palette.setColor(QPalette.Active,   QPalette.Link, QColor(100, 100, 230))
        palette.setColor(QPalette.Inactive, QPalette.Link, QColor(100, 100, 230))
        palette.setColor(QPalette.Disabled, QPalette.LinkVisited, QColor(74, 34, 74))
        palette.setColor(QPalette.Active,   QPalette.LinkVisited, QColor(230, 100, 230))
        palette.setColor(QPalette.Inactive, QPalette.LinkVisited, QColor(230, 100, 230))
        app.setPalette(palette)

    elif using_Qt4 or qWebKitMajorVersion() < 538:
        QMessageBox.warning(None,
                            "MOD-App Alert", # app.translate("HostWindow", ), #app.translate("HostWindow",
                            """
                              The WebKit included in your distribution's PyQt5 package is too old!<br/>
                              You might experience graphical issues in MOD-App.
                            """,
                            QMessageBox.Ok)

    pedalboardToLoad = ""

    # --------------------------------------------------------------------------------------------------------
    # Set-up custom signal handling

    setUpSignals()

    # --------------------------------------------------------------------------------------------------------
    # Check arguments

    if len(sys.argv) > 1:
        arg = sys.argv[-1]

        if os.path.exists(arg):
            pedalboardToLoad = arg

    # --------------------------------------------------------------------------------------------------------
    # Create GUI

    gui = HostWindow()

    if pedalboardToLoad:
        gui.openPedalboardLater(pedalboardToLoad)

    # --------------------------------------------------------------------------------------------------------
    # Show GUI

    gui.show()

    # --------------------------------------------------------------------------------------------------------
    # App-Loop

    sys.exit(app.exec_())

# ------------------------------------------------------------------------------------------------------------
